SET SEARCH_PATH = 'thebestdbever';

-- AI Generated from something like the following prompt - followed by some
--   REGX find and replace.
-- Can you give me a CSV list of 15 cocktail names, descriptions, allergens,
--  and prices like you would find at a fancy restaurant?
--  The CSV should have values in single quotes and each row
--  should be encased in ().

-- Appetizer, soup, salad, entree, dessert, cocktail, wine, drink
INSERT INTO menu_item (type, title, description, allergens, price, active)
    VALUES ('Cocktail', 'Spiced Pear Martini', 'Aromatic pear vodka, pear brandy, lemon juice, and a touch of cinnamon. ', 'Gluten-free', 18.99, TRUE),
           ('Cocktail', 'Elderflower Spritz', 'Sparkling wine, elderflower liqueur, soda water, and a sprig of mint. ', 'Gluten-free', 15.99, TRUE),
           ('Cocktail', 'Negroni Sbagliato', 'Campari, sweet vermouth, and prosecco for a lighter twist on the classic. ', 'Gluten-free', 16.99, TRUE),
           ('Cocktail', 'Smoked Old Fashioned', 'Bourbon, maple syrup, bitters, and a touch of smoke for a unique twist. ', 'Gluten-free', 19.99, TRUE),
           ('Cocktail', 'Espresso Martini', 'Coffee liqueur, vodka, espresso, and a sugar rim for a caffeine kick. ', 'Dairy', 17.99, TRUE),
           ('Cocktail', 'French 75', 'Gin, champagne, lemon juice, and sugar for a bubbly and refreshing drink. ', 'Gluten-free', 16.99, TRUE),
           ('Cocktail', 'Margarita (Classic or Spicy)', 'Tequila, lime juice, and orange liqueur. Spicy version adds jalapeño. ', 'Gluten-free', 15.99, TRUE),
           ('Cocktail', 'Dark & Stormy', 'Dark rum, ginger beer, and a lime wedge for a bold and spicy drink. ', 'Gluten-free', 14.99, TRUE),
           ('Cocktail', 'Moscow Mule', 'Vodka, ginger beer, lime juice, and served in a copper mug. ', 'Gluten-free', 15.99, TRUE),
           ('Cocktail', 'Aperol Spritz', 'Aperol, prosecco, and soda water for a light and refreshing Italian aperitif. ', 'Gluten-free', 14.99, TRUE),
           ('Cocktail', 'Aviation Gin Cocktail', 'Gin, maraschino liqueur, lemon juice, and a violet flower for a floral touch. ', 'Gluten-free', 18.99, TRUE),
           ('Cocktail', 'Paloma', 'Tequila, grapefruit soda, and a lime wedge for a citrusy and refreshing drink. ', 'Gluten-free', 14.99, TRUE),
           ('Cocktail', 'Bramble', 'Gin, lemon juice, sugar syrup, and muddled blackberries for a sweet and tart cocktail. ', 'Gluten-free', 17.99, TRUE),
           ('Cocktail', 'Old Fashioned', 'Bourbon, sugar, bitters, and a citrus peel for a timeless classic. ', 'Gluten-free', 18.99, TRUE),
           ('Cocktail', 'Daiquiri (Classic or Hemingway)', 'Rum, lime juice, and simple syrup. Hemingway version adds grapefruit juice. ', 'Gluten-free', 15.99, TRUE),
           ('Cocktail', 'Tommy`s Margarita', 'Tequila, lime juice, AND agave nectar FOR a more balanced margarita.', 'Gluten-free', 16.99, TRUE),
           ('Cocktail', ' Paper Plane ', ' Bourbon, Aperol, Amaro Nonino, AND lemon juice FOR a complex AND flavorful drink.', 'Gluten-free', 19.99, TRUE),
           ('Cocktail', ' Penicillin ', ' Scotch, honey syrup, lemon juice, AND ginger FOR a soothing AND warming cocktail.', 'Gluten-free', 18.99, TRUE),
           ('Cocktail', ' Bees Knees ', ' Gin, lemon juice, AND honey syrup FOR a SIMPLE AND elegant drink.', 'Gluten-free', 15.99, TRUE),
           ('Cocktail', ' Blood Orange Margarita ', ' Tequila, blood orange juice, lime juice, AND agave nectar FOR a UNIQUE twist.', 'Gluten-free', 16.99, TRUE),
           ('Cocktail', ' French Martini ', ' Vodka, Chambord, AND pineapple juice FOR a sweet AND fruity drink.', 'Dairy', 17.99, FALSE),
           ('Cocktail', ' Negroni ', ' Gin, Campari, AND sweet vermouth FOR a classic AND bitter Italian cocktail.', 'Gluten-free', 16.99, FALSE),
           ('Cocktail', ' East India Gimlet ', ' Gin, lime juice, AND a touch OF Persian lime cordial FOR a UNIQUE twist.', 'Gluten-free', 17.99, FALSE),
           ('Cocktail', ' Aviation ', ' Gin, maraschino liqueur, lemon juice, AND a cherry FOR a classic cocktail.', 'Gluten-free', 18.99, FALSE),
           ('Cocktail', ' Southside ', ' Gin, cucumber, lime juice, AND SIMPLE syrup FOR a refreshing AND light drink.', 'Gluten-free', 16.99, FALSE),
           ('Cocktail', ' Black Manhattan ', ' Rye whiskey, sweet vermouth, AND Maraschino liqueur FOR a smoky twist ON the classic.', 'Gluten-free', 19.99, FALSE),
           ('Cocktail', ' Boulevardier ', ' Campari, sweet vermouth, AND bourbon FOR a Negroni riff WITH a bolder spirit base.', 'Gluten-free', 17.99, FALSE),
           ('Cocktail', ' Bijou ', ' Gin, sweet vermouth, AND orange liqueur FOR a complex AND flavorful drink.', 'Gluten-free', 18.99, FALSE),
           ('Appetizer', 'Seared Day Scallops with Lemon Risotto and Asparagus Spears', 'Pan-seared scallops atop creamy lemon risotto with fresh asparagus spears. ', 'Gluten-free', 24.99, TRUE),
           ('Appetizer', 'Wagyu Beef Carpaccio with Truffle Aioli and Parmesan Crisps', 'Thinly sliced Wagyu beef drizzled with truffle aioli and served with crispy Parmesan cheese. ', 'Dairy', 28.99, TRUE),
           ('Appetizer', 'Wood-Roasted Cauliflower Steak with Romesco Sauce and Hazelnuts', 'Hearty cauliflower steak roasted to perfection and finished with a vibrant romesco sauce and toasted hazelnuts.', 'Vegan, Gluten-free', 18.99, TRUE),
           ('Appetizer', 'Lobster and Crab Bisque with Cognac Cream', 'Rich and creamy bisque overflowing with succulent lobster and crab meat, infused with cognac for a touch of warmth.', 'Gluten-free, Shellfish', 22.99, TRUE),
           ('Appetizer', 'Duck Confit Spring Rolls with Hoisin Dipping Sauce', 'Crispy spring rolls filled with shredded duck confit, served with a sweet and savory hoisin dipping sauce. ', 'Gluten-free', 16.99, TRUE),
           ('Appetizer', 'Marinated Heirloom Tomatoes with Burrata and Basil Pesto', 'Heirloom tomatoes bursting with flavor, paired with creamy burrata and a fragrant basil pesto. ', 'Dairy', 19.99, TRUE),
           ('Appetizer', 'Seared Foie Gras with Sautéed Apples and Port Wine Reduction', 'Luxurious foie gras pan-seared and served with sautéed apples and a rich port wine reduction. ', 'Gluten-free', 26.99, FALSE),
           ('Appetizer', 'Grilled Octopus with Charred Lemon and Paprika Oil', 'Tender slices of grilled octopus drizzled with a vibrant paprika oil and finished with charred lemon wedges. ', 'Gluten-free', 21.99, FALSE),
           ('Appetizer', 'Lamb Lollipops with Mint Gremolata and Fig Jam', 'Succulent lamb cubes grilled on skewers, accompanied by a zesty mint gremolata and a sweet fig jam. ', 'Gluten-free', 20.99, FALSE),
           ('Appetizer', 'Carpaccio of Tuna with Avocado, Ponzu Sauce, and Sesame Seeds', 'Thinly sliced tuna drizzled with a zesty ponzu sauce, served with sliced avocado and a sprinkle of sesame seeds. ', 'Gluten-free', 18.99, FALSE),
           ('Appetizer', 'Crispy Calamari with Spicy Marinara Aioli', 'Lightly fried calamari rings served with a flavorful and slightly spicy marinara aioli for dipping. ', 'Gluten-free', 15.99, FALSE),
           ('Appetizer', 'Roasted Bone Marrow with Parsley Gremolata and Toast Points', 'Roasted bone marrow served with a flavorful parsley gremolata and toasted bread points for scooping. ', 'Gluten-free', 17.99, FALSE),
           ('Appetizer', 'Escargots in Puff Pastry with Garlic Herb Butter', 'Classic French preparation of escargots baked in a decadent puff pastry shell with garlic herb butter. ', 'Dairy', 22.99, FALSE),
           ('Appetizer', 'Wild Mushroom Arancini with Truffle Oil', 'Crispy risotto balls filled with a medley of wild mushrooms and drizzled with fragrant truffle oil. ', 'Gluten-free', 16.99, FALSE),
           ('Appetizer', 'Pan-Seared Diver Scallops with Creamy Polenta and Crispy Prosciutto', 'Seared diver scallops presented atop creamy polenta, finished with crispy prosciutto for a textural contrast. ', 'Gluten-free', 23.99, TRUE),
           ('Soup', 'Roasted Butternut Squash Soup with Sage Cream', 'Velvety smooth soup made with roasted butternut squash, finished with a touch of sage cream. ', 'Gluten-free, Dairy', 14.99, TRUE),
           ('Soup', 'French Onion Soup (Gratinée)', 'Classic French onion soup with caramelized onions, rich beef broth, and a toasted baguette topped with melted Gruyère cheese. ', 'Gluten-free option available, Dairy', 18.99, FALSE),
           ('Soup', 'Chilled Cucumber Soup with Dill and Yogurt', 'Refreshing chilled soup featuring cucumber, dill, and yogurt, perfect for a warm starter. ', 'Gluten-free', 12.99, TRUE),
           ('Soup', 'Tomato Bisque with Burrata and Basil Oil', 'Rich and creamy tomato bisque topped with a dollop of fresh burrata and a drizzle of fragrant basil oil. ', 'Gluten-free option available, Dairy', 16.99, FALSE),
           ('Soup', 'Lentil Soup with Smoked Paprika and Chorizo (optional)', 'Hearty lentil soup flavored with smoked paprika. Can be made vegetarian or include optional chorizo for a smoky twist. ', 'Gluten-free', 15.99, FALSE),
           ('Soup', 'Spicy Thai Coconut Curry Soup with Vegetables and Shrimp', 'Flavorful Thai curry soup infused with coconut milk, vegetables, and succulent shrimp. ', 'Gluten-free, Shellfish', 18.99, FALSE),
           ('Soup', 'Cream of Wild Mushroom Soup with Truffle Oil', 'Creamy soup brimming with wild mushrooms and finished with a touch of truffle oil for an earthy aroma. ', 'Gluten-free option available, Dairy', 19.99, TRUE),
           ('Soup', 'Split Pea Soup with Country Ham and Herbs', 'Classic split pea soup featuring chunks of country ham and a blend of fresh herbs. ', 'Gluten-free option available, Pork', 17.99, FALSE),
           ('Soup', 'Minestrone Soup with Pesto and Parmesan Crisps', 'Traditional Italian minestrone soup packed with vegetables and pasta, finished with a dollop of pesto and Parmesan crisps. ', 'Gluten-free option available, Dairy', 16.99, FALSE),
           ('Soup', 'Chilled Gazpacho with Grilled Shrimp and Toasted Crostini', 'Refreshing chilled Spanish gazpacho soup with chunks of grilled shrimp and toasted crostini for dipping. ', 'Gluten-free option available', 15.99, FALSE),
           ('Soup', 'Roasted Corn and Crab Chowder with Smoked Paprika Oil', 'Creamy corn chowder loaded with crab meat and finished with a drizzle of smoked paprika oil for a touch of smokiness. ', 'Gluten-free option available, Shellfish', 20.99, FALSE),
           ('Soup', 'Curried Butternut Squash Soup with Coconut Milk and Naan Bread', 'Flavorful curried butternut squash soup made with coconut milk, served with warm naan bread for dipping. ', 'Gluten-free option available, Dairy', 14.99, FALSE),
           ('Salad', 'Heirloom Tomato and Burrata Salad with Basil Pesto', 'Arugula base topped with a variety of heirloom tomatoes, creamy burrata cheese, and a drizzle of fragrant basil pesto. ', 'Gluten-free', 18.99, TRUE),
           ('Salad', 'Seared Ahi Tuna Salad with Miso Glaze and Sesame Soba Noodles', 'Seared ahi tuna served over a bed of cold sesame soba noodles, finished with a sweet and savory miso glaze. ', 'Gluten-free option available', 22.99, TRUE),
           ('Salad', 'Grilled Chicken Caesar Salad (Classic or Vegetarian with Tofu)', 'Crisp romaine lettuce tossed with creamy Caesar dressing, parmesan cheese, and croutons. Choose classic with grilled chicken or vegetarian option with pan-seared tofu. ', 'Gluten-free option available, Dairy', 16.99, TRUE),
           ('Salad', 'Baby Kale Salad with Roasted Beets, Goat Cheese, and Candied Pecans', 'Tender baby kale tossed with roasted beets, crumbled goat cheese, and candied pecans for a sweet and savory combination. ', 'Gluten-free option available, Dairy', 17.99, FALSE),
           ('Salad', 'Quinoa Salad with Roasted Vegetables and Lemon Vinaigrette', 'Protein-packed quinoa salad featuring roasted vegetables like zucchini, peppers, and eggplant, dressed with a refreshing lemon vinaigrette. ', 'Gluten-free, Vegan', 15.99, FALSE),
           ('Salad', 'Wedge Salad with Blue Cheese Dressing, Bacon, and Cherry Tomatoes', 'Classic wedge of iceberg lettuce served with crumbled blue cheese dressing, crispy bacon bits, and sweet cherry tomatoes. ', 'Gluten-free option available, Dairy', 14.99, FALSE),
           ('Salad', 'Fennel and Blood Orange Salad with Mint and Pistachios', 'Refreshing salad with shaved fennel, sliced blood orange, fresh mint, and chopped pistachios for a delightful textural contrast. ', 'Gluten-free, Vegan', 16.99, FALSE),
           ('Salad', 'Seared Scallop Salad with Lemon Risotto and Asparagus', 'Pan-seared scallops presented on a bed of creamy lemon risotto, surrounded by asparagus spears and dressed with a light vinaigrette. ', 'Gluten-free option available', 24.99, FALSE),
           ('Salad', 'Steak Salad with Gorgonzola Cheese, Caramelized Onions, and Truffle Vinaigrette', 'Sliced grilled steak served over mixed greens with crumbles of gorgonzola cheese, caramelized onions, and a truffle vinaigrette. ', 'Gluten-free option available, Dairy', 26.99, FALSE),
           ('Salad', 'Chopped Thai Salad with Peanut Dressing and Shrimp', 'Mixture of chopped vegetables, herbs, and succulent shrimp tossed in a flavorful peanut dressing for a taste of Thailand. ', 'Gluten-free option available, Shellfish, Peanuts', 18.99, FALSE),
           ('Entree', 'Pan-Seared Duck Breast with Cherry Sauce and Pistachio Brioche', 'Duck breast cooked to perfection, served with a sweet and tart cherry sauce and a decadent pistachio brioche. ', 'Gluten-free option available', 32.99, TRUE),
           ('Entree', 'Grilled Chilean Sea Bass with Lemon Caper Butter and Asparagus', 'Flaky Chilean sea bass grilled to perfection, finished with a vibrant lemon caper butter sauce and asparagus spears. ', 'Gluten-free', 28.99, TRUE),
           ('Entree', 'Seared Diver Scallops with Creamy Risotto andCrispy Prosciutto', 'Seared scallops presented atop creamy risotto, finished with crispy prosciutto for a textural contrast. ', 'Gluten-free', 29.99, TRUE),
           ('Entree', 'Roasted Rack of Lamb with Mint Jus and Garlic Mashed Potatoes', 'Herb-crusted rack of lamb roasted to a beautiful medium-rare, served with a flavorful mint jus and creamy garlic mashed potatoes. ', 'Gluten-free option available', 36.99, TRUE),
           ('Entree', 'Pan-Seared Filet Mignon with Truffle Butter and Roasted Fingerling Potatoes', 'Tender filet mignon pan-seared to your preference, topped with decadent truffle butter, and accompanied by roasted fingerling potatoes. ', 'Gluten-free option available, Dairy', 42.99, TRUE),
           ('Entree', 'Branzino (Mediterranean Sea Bass) with Tomato Confit and Lemon Thyme Sauce', 'Whole branzino fish baked with a flavorful tomato confit and finished with a light lemon thyme sauce. ', 'Gluten-free', 34.99, FALSE),
           ('Entree', 'Pan-Roasted Chicken Breast with Morels and Creamy Polenta', 'Succulent chicken breast pan-roasted with a medley of morel mushrooms, served over creamy polenta for a comforting dish. ', 'Gluten-free option available', 26.99, FALSE),
           ('Entree', 'Braised Short Rib with Red Wine Reduction and Root Vegetables', 'Tender short rib slow-braised in red wine until meltingly delicious, served with a rich reduction and roasted root vegetables. ', 'Gluten-free option available', 38.99, FALSE),
           ('Entree', 'Pan-Seared Salmon with Roasted Brussels Sprouts and Lemon Dill Sauce', 'Fresh salmon pan-seared to your liking, accompanied by roasted Brussels sprouts and a light lemon dill sauce. ', 'Gluten-free', 30.99, FALSE),
           ('Entree', 'Vegetable Wellington with Roasted Butternut Squash and Sage Cream', 'Puff pastry filled with a flavorful vegetable medley, served with roasted butternut squash and a decadent sage cream sauce. ', 'Vegan, Gluten-free', 28.99, FALSE),
           ('Entree', 'Tagliatelle with Porcini Mushrooms and Black Truffle Shavings', 'Homemade tagliatelle pasta tossed with a luxurious porcini mushroom sauce and finished with black truffle shavings for an extra touch of elegance. ', 'Gluten-free option available, Dairy', 34.99, FALSE),
           ('Entree', 'Lobster Ravioli with Brown Butter Sage Sauce', 'Tender ravioli filled with succulent lobster meat, bathed in a flavorful brown butter sage sauce. ', 'Gluten-free option available, Shellfish, Dairy', 38.99, FALSE),
           ('Entree', 'Pan-Seared Duck Breast with Fig Compote and Pistachio Crust', 'Duck breast crusted with pistachios and pan-seared to perfection, served with a sweet and savory fig compote. ', 'Gluten-free option available', 34.99, FALSE),
           ('Entree', 'Grilled New York Strip Steak with Gorgonzola Butter and Rosemary Fries', 'Classic New York strip grilled to your desired doneness, topped with a creamy gorgonzola butter, and served with crispy rosemary fries. ', 'Gluten-free option available, Dairy', 36.99, FALSE),
           ('Entree', 'Pan-Seared Scallops with Lobster Risotto and Saffron Sauce', 'Seared scallops presented atop a luxurious lobster risotto, finished with a vibrant saffron sauce. ', 'Gluten-free option available, Shellfish', 40.99, FALSE),
           ('Entree', 'Roasted Chicken with Lemon and Herbs', 'Whole roasted chicken seasoned with fresh herbs and lemon, perfect for a comforting and flavorful main course. ', 'Gluten-free', 24.99, FALSE),
           ('Entree', 'Dover Sole Meunière with Lemon Caper Butter and Brown Butter Potatoes', 'Delicate Dover sole pan-fried in a classic meunière style, finished with a lemon caper butter sauce and brown butter potatoes. ', 'Gluten-free option available, Dairy', 32.99, FALSE),
           ('Entree', 'Spiced Moroccan Lamb Tagine with Couscous', 'Tender lamb slow-cooked in a fragrant Moroccan tagine with spices, served with fluffy couscous. ', 'Gluten-free option available', 34.99, FALSE),
           ('Entree', 'Pan-Seared Ahi Tuna with Wasabi Pea Crust and Sesame Soba Noodles', 'Ahi tuna crusted with wasabi peas and pan-seared to a perfect sear, served over cold sesame soba noodles. ', 'Gluten-free option available', 30.99, FALSE),
           ('Dessert', 'Chocolate Lava Cake with Vanilla Bean Ice Cream', 'Warm chocolate cake with a molten chocolate center, served with a scoop of vanilla bean ice cream. ', 'Gluten-free option available, Dairy', 12.99, FALSE),
           ('Dessert', 'Decadent Flourless Chocolate Cake with Raspberry Coulis', 'Dense and rich flourless chocolate cake, perfect for those who love intense chocolate flavor. Accompanied by a tart raspberry coulis. ', 'Gluten-free, Dairy', 14.99, FALSE),
           ('Dessert', 'Crème Brûlée with Seasonal Berries', 'Classic crème brûlée with a caramelized sugar crust, served with a selection of fresh seasonal berries. ', 'Gluten-free option available, Dairy', 10.99, FALSE),
           ('Dessert', 'Vanilla Panna Cotta with Mango Salsa and Coconut Tuile', 'Light and creamy panna cotta with a touch of vanilla, topped with a vibrant mango salsa and a crisp coconut tuile. ', 'Gluten-free option available, Dairy', 11.99, FALSE),
           ('Dessert', 'Warm Apple Crisp with Vanilla Ice Cream and Caramel Sauce', 'Classic apple crisp with a warm and gooey filling, served with a scoop of vanilla ice cream and drizzled with caramel sauce. ', 'Gluten-free option available, Dairy', 12.99, FALSE),
           ('Dessert', 'Selection of Artisanal Cheeses with Fruit and Honey', 'A curated selection of artisanal cheeses paired with seasonal fruits and a drizzle of honey. ', 'Dairy', 16.99, FALSE),
           ('Dessert', 'Deconstructed Lemon Tart with Meringue and Shortbread Crumble', 'Modern take on a lemon tart with a base of shortbread crumble, topped with a light lemon curd and meringue shards. ', 'Gluten-free option available, Dairy', 13.99, FALSE),
           ('Dessert', 'Chocolate and Hazelnut Mousse with Chocolate Ganache', 'Rich and decadent chocolate mousse swirled with hazelnut praline, finished with a dark chocolate ganache. ', 'Gluten-free option available, Dairy', 14.99, FALSE),
           ('Dessert', 'Seasonal Fruit Tart with Almond Frangipane', 'Fresh seasonal fruits baked into a buttery crust with a layer of almond frangipane for a delightful combination. ', 'Gluten-free option available, Dairy', 12.99, FALSE),
           ('Dessert', 'Warm Bread Pudding with Spiced Pear Compote and Vanilla Sauce', 'Classic bread pudding with a warm and comforting texture, topped with a spiced pear compote and drizzled with vanilla sauce. ', 'Gluten-free option available, Dairy', 11.99, FALSE),
           ('Dessert', 'Coconut Panna Cotta with Mango Sorbet and Passion Fruit Sauce', 'Light and creamy coconut panna cotta served with refreshing mango sorbet and drizzled with a tart passion fruit sauce. ', 'Gluten-free, Vegan', 12.99, TRUE),
           ('Dessert', 'Chocolate Soufflé with Raspberry Coulis', 'Classic chocolate soufflé with a light and airy texture, served with a tart raspberry coulis. ', 'Gluten-free option available, Dairy', 15.99, TRUE),
           ('Dessert', 'Selection of Sorbets and Gelatos (Choose 3)', 'Choose three scoops from our selection of house-made sorbets and gelatos for a refreshing and flavorful ending. ', 'Vegan options available', 10.99, TRUE),
           ('Dessert', 'Tiramisu Classico', 'Classic Italian dessert with ladyfingers dipped in espresso, layered with mascarpone cream, and dusted with cocoa powder. ', 'Gluten-free option available, Dairy', 11.99, TRUE),
           ('Dessert', 'Cheesecake with Seasonal Fruit Compote', 'Rich and creamy cheesecake on a buttery crust, topped with a seasonal fruit compote. ', 'Gluten-free option available, Dairy', 12.99, TRUE)
;


-- AI Generated from something like the following prompt - followed by some
--   REGX find and replace.
-- Can you give me a CSV list of 20 wine names, descriptions, a random integer
--  between 0 and 10, and prices per bottle like you would find at a
--  fancy restaurant?
--  The CSV should have values in single quotes and each row should be
--  encased in ().

-- Wines
INSERT INTO menu_item (type, title, description, price, quantity, active)
    VALUES ('Wine', 'Marques de Riscal Reserva Rioja Tempranillo (Spain, Rioja)', 'Aromas of red fruit and spice with a smooth finish.', 38.99, 7, TRUE),
           ('Wine', 'Sancerre Louis Jadot (France, Loire Valley)', 'Crisp and mineral Sauvignon Blanc with citrus and white flower notes.', 42.99, 9, TRUE),
           ('Wine', 'Masi Campofiorin Ripasso (Italy, Valpolicella)', 'Bold and dry blend of Corvina, Rondinella, and Molinara grapes.', 55.99, 5, TRUE),
           ('Wine', 'Cloudy Bay Sauvignon Blanc (New Zealand, Marlborough)', 'Expressive Sauvignon Blanc with gooseberry, passion fruit, and herbaceous aromas.', 48.99, 3, TRUE),
           ('Wine', 'Domaine Drouhin Pinot Noir (France, Oregon)', 'Light-bodied Pinot Noir with cherry, raspberry, and earthy notes.', 62.99, 2, TRUE),
           ('Wine', 'Stag`s Leap Napa Cabernet Sauvignon (USA, California)', 'Full-bodied Cabernet Sauvignon with dark fruit, cedar, and leather aromas.', 85.99, 8, TRUE),
           ('Wine', 'Gérard Bertrand Côtes-du-Rhône Rosé (France, Rhône Valley)', 'Dry and refreshing rosé with notes of strawberry, watermelon, and minerality.', 45.99, 10, TRUE),
           ('Wine', 'Grüner Veltliner Weingut Bründlmayer Kamptal (Austria, Wachau Valley)', 'Crisp and peppery Grüner Veltliner with citrus and white pepper aromas.', 40.99, 4, TRUE),
           ('Wine', 'Barolo Marchesi di Barolo (Italy, Piedmont)', 'Powerful and complex Barolo with notes of tar, rose, and black cherry.', 98.99, 6, TRUE),
           ('Wine', 'Newton Chardonnay (USA, California)', 'Rich and buttery Chardonnay with oak, vanilla, and tropical fruit aromas.', 52.99, 1, TRUE),
           ('Wine', 'Saint-Emilion Château Canon (France, Bordeaux)', 'Right Bank Bordeaux blend with Merlot and Cabernet Franc.', 72.99, 0, FALSE),
           ('Wine', 'Cloudy Bay Pinot Noir (New Zealand, Central Otago)', 'Elegant and complex Pinot Noir with red fruit, earth, and floral notes.', 68.99, 7, TRUE),
           ('Wine', 'Bodegas Roda Rioja Crianza Tempranillo (Spain, Rioja)', 'Tempranillo with good structure and aromas of red fruit and spice.', 44.99, 9, TRUE),
           ('Wine', 'Soave Classico Pieropan (Italy, Veneto)', 'Crisp and mineral Soave made from Garganega grapes.', 38.99, 5, TRUE),
           ('Wine', 'The Prisoner Cabernet Sauvignon (USA, Napa Valley)', 'Bold and opulent Cabernet Sauvignon with dark fruit, chocolate, and cedar aromas.', 75.99, 3, TRUE),
           ('Wine', 'Judd`s Hill Chardonnay (USA, Anderson Valley)', 'Unoaked Chardonnay with citrus, melon, and mineral notes.', 46.99, 8, TRUE),
           ('Wine', 'Malbec Trapiche Broquel (Argentina, Mendoza)', 'Juicy and expressive Malbec with plum, blackberry, and violet aromas.', 39.99, 2, TRUE),
           ('Wine', 'Champagne Ayala Brut Majeur (France, Champagne)', 'Balanced and elegant Champagne with notes of citrus, brioche, and minerality.', 78.99, 0, FALSE),
           ('Wine', 'Pinot Grigio Santa Margherita (Italy, Alto Adige)', 'Light-bodied Pinot Grigio with crisp acidity and apple, pear, and citrus aromas.', 42.99, 6, TRUE),
           ('Wine', 'Sokol Blossum Riesling (Austria, Wachau Valley)', 'Aromatic Riesling with notes of honeysuckle, peach, and petrol.', 45.99, 7, TRUE),
           ('Wine', 'Meursault Domaine Jean-Marc Pillot (France, Burgundy)', 'Rich and creamy Chardonnay from the renowned Meursault region.', 82.99, 2, TRUE),
           ('Wine', 'Barbera d`Alba Paolo Scavino (Italy, Piedmont)', 'Bold and juicy Barbera with flavors of black cherry, plum, and earth.', 58.99, 9, TRUE),
           ('Wine', 'Pinot Noir Willamette Valley Shea Wine Cellars (USA, Oregon)', 'Earthy and elegant Pinot Noir with notes of raspberry, mushroom, and forest floor.', 65.99, 4, TRUE),
           ('Wine', 'Sauvignon Blanc Kim Crawford (New Zealand, Marlborough)', 'Expressive Sauvignon Blanc with gooseberry, passion fruit, and grassy aromas.', 40.99, 3, TRUE),
           ('Wine', 'Châteauneuf-du-Pape Domaine du Vieux Télégraphe (France, Rhône Valley)', 'Powerful blend of Grenache, Syrah, and Mourvèdre with notes of black fruit, spice, and leather.', 110.99, 8, TRUE),
           ('Wine', 'Prosecco Valdobbiadene DOCG Bisol Crede (Italy, Veneto)', 'Sparkling Prosecco with lively bubbles and aromas of pear, apple, and citrus.', 52.99, 1, TRUE),
           ('Wine', 'Tempranillo Ribera del Duero Bodegas Pesquera (Spain, Ribera del Duero)', 'Full-bodied Tempranillo with rich flavors of plum, blackberry, and licorice.', 78.99, 0, FALSE),
           ('Wine', 'Viognier Condrieu Domaine Georges Vernay (France, Rhône Valley)', 'Aromatic and floral Viognier with notes of apricot, peach, and honeysuckle.', 62.99, 5, TRUE),
           ('Wine', 'Zinfandel Ridge Lytton Springs (USA, California)', 'Bold and spicy Zinfandel with flavors of blackberry, pepper, and jammy fruit.', 55.99, 6, TRUE),
           ('Wine', 'Sancerre Domaine Alphonse Mellot (France, Loire Valley)', 'Crisp and mineral Sauvignon Blanc with citrus, white flower, and flint aromas.', 48.99, 10, TRUE),
           ('Wine', 'Amarone della Valpolicella Zenato (Italy, Valpolicella)', 'Rich and dried fruit-forward Amarone with notes of raisin, prune, and spice.', 92.99, 4, TRUE),
           ('Wine', 'Malbec Cahors Château du Gaudou (France, Cahors)', 'Bold and structured Malbec with flavors of black plum, earth, and leather.', 42.99, 7, TRUE),
           ('Wine', 'Grüner Veltliner Weingut Emmerich Knoll (Austria, Wachau Valley)', 'Crisp and refreshing Grüner Veltliner with citrus, white pepper, and mineral notes.', 38.99, 2, TRUE),
           ('Wine', 'Carmenère Santa Ema Reserva (Chile, Colchagua Valley)', 'Unique and herbaceous Carmenère with notes of red bell pepper, plum, and spice.', 44.99, 9, TRUE),
           ('Wine', 'Gewürztraminer Domaine Weinbach (France, Alsace)', 'Aromatic and spicy Gewürztraminer with notes of lychee, rosewater, and ginger.', 50.99, 3, TRUE),
           ('Wine', 'Cabernet Sauvignon Coonawarra Wynns Coonawarra Estate (Australia, Coonawarra)', 'Full-bodied and structured Cabernet Sauvignon with flavors of black currant, cassis, and eucalyptus.', 68.99, 8, TRUE),
           ('Wine', 'Pinot Grigio Friuli Grave La Tunella (Italy, Friuli-Venezia Giulia)', 'Light-bodied and mineral Pinot Grigio with crisp acidity and apple, pear, and citrus aromas.', 39.99, 5, TRUE),
           ('Wine', 'Blanc de Blancs Champagne Taittinger (France, Champagne)', 'Elegant and refined Champagne made exclusively from Chardonnay grapes.', 85.99, 0, FALSE),
           ('Wine', 'Tempranillo Rioja Alta R. López de Heredia Viña Tondonia (Spain, Rioja)', 'Classic Rioja with aged Tempranillo, offering notes of leather, tobacco, and dried fruit.', 72.99, 6, TRUE),
           ('Wine', 'Pouilly-Fuissé Domaine Leflaive (France, Burgundy)', 'Crisp and mineral Chardonnay with notes of citrus, white flowers, and hazelnut.', 95.99, 3, TRUE),
           ('Wine', 'Super Tuscan Sassicaia Tenuta San Guido (Italy, Tuscany)', 'Bold blend of Cabernet Sauvignon and Cabernet Franc with notes of black currant, cedar, and earth.', 120.99, 8, TRUE),
           ('Wine', 'Pinot Noir Dundee Hills Domaine Drouhin (USA, Oregon)', 'Light-bodied and elegant Pinot Noir with aromas of red cherry, raspberry, and spice.', 72.99, 5, TRUE),
           ('Wine', 'Sauvignon Blanc Marlborough Yealands (New Zealand, Marlborough)', 'Expressive Sauvignon Blanc with gooseberry, passion fruit, and tropical fruit aromas.', 48.99, 1, TRUE),
           ('Wine', 'Côtes du Rhône Châteauneuf-du-Pape Domaine Beaucastel (France, Rhône Valley)', 'Powerful and complex blend from the renowned Châteauneuf-du-Pape appellation.', 150.99, 0, FALSE),
           ('Wine', 'Franciacorta Ca` del Bosco Curtefranca (Italy, Lombardy)', 'Sparkling Franciacorta with fine bubbles and notes of citrus, white peach, and brioche.', 68.99, 7, TRUE),
           ('Wine', 'Tempranillo Rioja Bodegas Muga Crianza (Spain, Rioja)', 'Well-balanced Rioja with Tempranillo, offering notes of red fruit, spice, and earth.', 55.99, 2, TRUE),
           ('Wine', 'Viognier Condrieu Domaine Christine Vernay (France, Rhône Valley)', 'Aromatic and floral Viognier with notes of apricot, honeysuckle, and minerality.', 75.99, 9, TRUE),
           ('Wine', 'Syrah Hermitage E. Guigal (France, Rhône Valley)', 'Powerful and structured Syrah from the legendary Hermitage region.', 180.99, 4, TRUE),
           ('Wine', 'Pinot Noir Russian River Valley Dutton Estate (USA, California)', 'Rich and textured Pinot Noir with aromas of cherry, plum, and cola.', 82.99, 6, TRUE),
           ('Wine', 'Sancerre Domaine Vacheron (France, Loire Valley)', 'Crisp and mineral Sauvignon Blanc with citrus, white flower, and gunflint aromas.', 52.99, 10, TRUE),
           ('Wine', 'Barolo Serralunga d`Alba Giacomo Conterno (Italy, Piedmont)', 'Powerful and age-worthy Barolo with notes of tar, rose, and black cherry.', 220.99, 5, TRUE),
           ('Wine', 'Malbec Cahors Le Petit Clos (France, Cahors)', 'Medium-bodied Malbec with flavors of plum, earth, and violet.', 39.99, 7, TRUE),
           ('Wine', 'Grüner Veltliner Smaragd Weingut Prager (Austria, Wachau Valley)', 'Top-tier Grüner Veltliner with intense flavors of citrus, white pepper, and minerality.', 50.99, 2, TRUE),
           ('Wine', 'Carménère Maule Valley Montes Alpha (Chile, Maule Valley)', 'Bold and spicy Carmenère with pronounced notes of bell pepper, black fruit, and earth.', 46.99, 8, TRUE),
           ('Wine', 'Gewürztraminer Vendanges Tardives Domaine Weinbach (France, Alsace)', 'Rich and concentrated Gewürztraminer with notes of lychee, rosewater, and honey.', 65.99, 0, FALSE),
           ('Wine', 'Shiraz Barossa Valley Penfolds Grange (Australia, Barossa Valley)', 'Iconic Australian Shiraz with bold flavors of blackberry, plum, and spice.', 320.99, 9, TRUE),
           ('Wine', 'Pinot Grigio delle Venezie Santa Margherita (Italy, Various Regions)', 'Light-bodied Pinot Grigio with crisp acidity and apple, pear, and citrus aromas.', 42.99, 3, TRUE),
           ('Wine', 'Champagne Brut Rosé Laurent-Perrier (France, Champagne)', 'Elegant and balanced rosé Champagne with notes of strawberry, raspberry, and brioche.', 98.99, 6, TRUE),
           ('Wine', 'Priorat Álvaro Palacios Gratallops (Spain, Priorat)', 'Powerful and expressive red wine from the acclaimed Priorat region.', 110.99, 1, TRUE)
;